export const ADD_NEW_BET = 'ADD_NEW_BET';
export const SET_ACTIVE_TOKEN = 'SET_ACTIVE_TOKEN';

export const ENABLE_PLAYER_ENTRY = 'ENABLE_PLAYER_ENTRY';
export const DISABLE_PLAYER_ENTRY = 'DISABLE_PLAYER_ENTRY';

export const ACTIVATE_CRASH = 'ACTIVATE_CRASH';
export const DEACTIVATE_CRASH = 'DEACTIVATE_CRASH';

export const CASH_OUT = 'CASH_OUT';
export const ADJUST_CRASH_BALANCE = 'ADJUST_CRASH_BALANCE';
